# Generated by Django 3.1.7 on 2021-03-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_code', models.BinaryField()),
                ('image_type', models.CharField(default=False, max_length=20)),
                ('caption', models.CharField(default='IMG_CAPTION', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
                ('password', models.CharField(default='PASSWORD', max_length=100)),
            ],
        ),
    ]
