# Generated by Django 3.1.7 on 2021-03-17 01:45
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('imgstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_code', models.BinaryField(blank=True)),
                ('caption',models.CharField(max_length=100,default='IMG_CAPTION'))
            ],
        ),
    ]
