# Generated by Django 3.1.7 on 2021-03-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
