# Generated by Django 3.1.7 on 2021-03-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstore', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_code',
            field=models.BinaryField(),
        ),
    ]
