# Generated by Django 3.1.7 on 2021-03-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgstore', '0003_auto_20210317_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_type',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
